### ISSUE TITLE
/info command: provide sever specific statistics

### ISSUE THREAD

**Issue by starpause** [0x29a-blink/pollbot#1]
I would like to know who the top users of the bot are on my server so that I can reward them. Thanks!

**Comment by 0x29a-blink** [comment]
Could you please elaborate on what you mean by this? Do you mean a list of the users who've voted on a specific item in a poll or something else?

**Comment by starpause** [comment]
The #1 thing I'm interested in knowing who has participated the most across all polls run on my server on a monthly or weekly basis.
